---
version: '3.9'
services:
  plex:
    image: plexinc/pms-docker
    container_name: plex
    volumes:
      - plex_config:/config
      - /mnt/data/plex/transcode:/transcode
      - /mnt/data/media:/data
    network_mode: host
    restart: always
    environment:
      - PLEX_CLAIM="nope"
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Europe/Prague

  #tautulli:
  #  image: ghcr.io/linuxserver/tautulli
   # container_name: tautulli
    #depends_on:
    #  - plex
    #volumes:
#      - tautulli_data:/config
#    ports:
#      - 8181:8181
#    restart: unless-stopped
#    environment:
#      - PUID=${PUID}
#      - PGID=${PGID}
#      - TZ=Europe/Prague

#  plexrequests:
#    image: linuxserver/plexrequests
#    container_name: plexrequests
#    depends_on:
#      - plex
#    volumes:
#      - /opt/appdata/plexrequests:/config
#      - /mnt/storage/tv:/tv
#    ports:
#      - 27026:3000
#    links:
#      - plex
#    restart: always
#    environment:
#      - PUID=${PUID}
#      - PGID=${PGID}


volumes:
#  tautulli_data: {}
  plex_config: {}
